/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 comp.gltf --transform
Author: Daniel Cardona (https://sketchfab.com/DanielCardonaArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dream-computer-setup-82f78bbaf2d34f01af854a52151dbf49
Title: Dream Computer Setup
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/comp-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RTX2080ti" position={[0.022, -0.595, -8.096]}>
          <group name="LeftFan" position={[-1.694, -2.22, 4.765]}>
            <group name="pCylinder159" position={[-0.003, -0.021, -0.05]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="pCylinder159_RTXM2_0" geometry={nodes.pCylinder159_RTXM2_0.geometry} material={materials.RTXM2} />
            </group>
            <group name="pCube1186" position={[-0.003, -0.007, 0.001]} rotation={[0.393, -1.02, 0.453]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1186_RTXFanM1_0" geometry={nodes.pCube1186_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube997" position={[-0.003, -0.007, 0.001]} rotation={[0.877, -0.713, 1.073]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube997_RTXFanM1_0" geometry={nodes.pCube997_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube996" position={[-0.003, -0.007, 0.001]} rotation={[1.034, -0.33, 1.38]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube996_RTXFanM1_0" geometry={nodes.pCube996_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube1180" position={[-0.003, -0.007, 0.001]} rotation={[1.063, 0.104, 1.629]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1180_RTXFanM1_0" geometry={nodes.pCube1180_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube1178" position={[-0.003, -0.007, 0.001]} rotation={[0.984, 0.511, 1.885]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1178_RTXFanM1_0" geometry={nodes.pCube1178_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube993" position={[-0.003, -0.007, 0.001]} rotation={[0.707, 0.882, 2.305]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube993_RTXFanM1_0" geometry={nodes.pCube993_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube992" position={[-0.003, -0.007, 0.001]} rotation={[0.026, 1.066, 3.112]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube992_RTXFanM1_0" geometry={nodes.pCube992_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube991" position={[-0.003, -0.007, 0.001]} rotation={[-0.683, 0.898, -2.337]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube991_RTXFanM1_0" geometry={nodes.pCube991_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube1189" position={[-0.003, -0.007, 0.001]} rotation={[-0.978, 0.525, -1.896]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1189_RTXFanM1_0" geometry={nodes.pCube1189_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube989" position={[-0.003, -0.007, 0.001]} rotation={[-1.062, 0.119, -1.637]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube989_RTXFanM1_0" geometry={nodes.pCube989_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube1188" position={[-0.003, -0.007, 0.001]} rotation={[-1.04, -0.301, -1.398]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1188_RTXFanM1_0" geometry={nodes.pCube1188_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube1185" position={[-0.003, -0.007, 0.001]} rotation={[-0.875, -0.716, -1.069]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1185_RTXFanM1_0" geometry={nodes.pCube1185_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube986" position={[-0.003, -0.007, 0.001]} rotation={[-0.406, -1.017, -0.468]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube986_RTXFanM1_0" geometry={nodes.pCube986_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
          </group>
          <group name="RightFan" position={[2.5, -2.22, 4.765]}>
            <group name="pCylinder161" position={[-0.003, -0.021, -0.05]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh name="pCylinder161_RTXM2_0" geometry={nodes.pCylinder161_RTXM2_0.geometry} material={materials.RTXM2} />
            </group>
            <group name="pCube1181" position={[-0.003, -0.007, 0.001]} rotation={[0.877, -0.713, 1.073]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1181_RTXFanM1_0" geometry={nodes.pCube1181_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube1190" position={[-0.003, -0.007, 0.001]} rotation={[1.034, -0.33, 1.38]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1190_RTXFanM1_0" geometry={nodes.pCube1190_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube995" position={[-0.003, -0.007, 0.001]} rotation={[1.063, 0.104, 1.629]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube995_RTXFanM1_0" geometry={nodes.pCube995_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube994" position={[-0.003, -0.007, 0.001]} rotation={[0.984, 0.511, 1.885]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube994_RTXFanM1_0" geometry={nodes.pCube994_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube1182" position={[-0.003, -0.007, 0.001]} rotation={[0.707, 0.882, 2.305]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1182_RTXFanM1_0" geometry={nodes.pCube1182_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube1187" position={[-0.003, -0.007, 0.001]} rotation={[0.026, 1.066, 3.112]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1187_RTXFanM1_0" geometry={nodes.pCube1187_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube1179" position={[-0.003, -0.007, 0.001]} rotation={[-0.683, 0.898, -2.337]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1179_RTXFanM1_0" geometry={nodes.pCube1179_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube990" position={[-0.003, -0.007, 0.001]} rotation={[-0.978, 0.525, -1.896]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube990_RTXFanM1_0" geometry={nodes.pCube990_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube1183" position={[-0.003, -0.007, 0.001]} rotation={[-1.062, 0.119, -1.637]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1183_RTXFanM1_0" geometry={nodes.pCube1183_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube988" position={[-0.003, -0.007, 0.001]} rotation={[-1.04, -0.301, -1.398]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube988_RTXFanM1_0" geometry={nodes.pCube988_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube987" position={[-0.003, -0.007, 0.001]} rotation={[-0.875, -0.716, -1.069]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube987_RTXFanM1_0" geometry={nodes.pCube987_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube1184" position={[-0.003, -0.007, 0.001]} rotation={[-0.383, -1.023, -0.441]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube1184_RTXFanM1_0" geometry={nodes.pCube1184_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube998" position={[-0.003, -0.007, 0.001]} rotation={[0.393, -1.02, 0.453]} scale={[2.365, 1, 1.284]}>
              <mesh name="pCube998_RTXFanM1_0" geometry={nodes.pCube998_RTXFanM1_0.geometry} material={materials.PaletteMaterial001} />
            </group>
          </group>
        </group>
        <group name="Corsair_Fan" position={[9.983, -0.168, -7.023]} rotation={[Math.PI / 2, 0, 0]} scale={[0.576, 0.704, 0.576]}>
          <group name="Fan2" position={[0.033, -0.014, 0]} scale={[0.772, 0.762, 0.772]}>
            <group name="pCube967" position={[-0.895, -0.055, 1.049]} rotation={[1.217, 0.63, -0.692]} scale={[1, 1, 0.267]}>
              <mesh name="pCube967_RGBM_0" geometry={nodes.pCube967_RGBM_0.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube966" position={[0.161, -0.055, 1.344]} rotation={[1.885, 0.648, -1.746]} scale={[1, 1, 0.267]}>
              <mesh name="pCube966_RGBM_0" geometry={nodes.pCube966_RGBM_0.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube965" position={[1.15, -0.055, 0.67]} rotation={[2.263, 0.175, -2.615]} scale={[1, 1, 0.267]}>
              <mesh name="pCube965_RGBM_0" geometry={nodes.pCube965_RGBM_0.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube964" position={[1.243, -0.055, -0.468]} rotation={[2.189, -0.376, 2.984]} scale={[1, 1, 0.267]}>
              <mesh name="pCube964_RGBM_0" geometry={nodes.pCube964_RGBM_0.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube963" position={[0.291, -0.055, -1.319]} rotation={[1.566, -0.71, 1.883]} scale={[1, 1, 0.267]}>
              <mesh name="pCube963_RGBM_0" geometry={nodes.pCube963_RGBM_0.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube962" position={[-0.936, -0.055, -1.014]} rotation={[0.953, -0.376, 0.795]} scale={[1, 1, 0.267]}>
              <mesh name="pCube962_RGBM_0" geometry={nodes.pCube962_RGBM_0.geometry} material={materials.RGBM} />
            </group>
            <group name="pCylinder145">
              <mesh name="pCylinder145_Fan2M_0" geometry={nodes.pCylinder145_Fan2M_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube961" position={[-1.39, -0.055, 0]} rotation={[0.875, 0.159, 0.131]} scale={[1, 1, 0.267]}>
              <mesh name="pCube961_RGBM_0" geometry={nodes.pCube961_RGBM_0.geometry} material={materials.RGBM} />
            </group>
            <group name="pCylinder164" scale={[1.189, 0.94, 1.189]}>
              <mesh name="pCylinder164_RGBM_0" geometry={nodes.pCylinder164_RGBM_0.geometry} material={materials.RGBM} />
            </group>
          </group>
        </group>
        <group name="Corsair_Fan1" position={[9.983, -3.725, -7.023]} rotation={[Math.PI / 2, 0, 0]} scale={[0.576, 0.704, 0.576]}>
          <group name="Fan2_1" position={[0.033, -0.014, 0]} scale={[0.772, 0.762, 0.772]}>
            <group name="pCube967_1" position={[-0.895, -0.055, 1.049]} rotation={[1.217, 0.63, -0.692]} scale={[1, 1, 0.267]}>
              <mesh name="pCube967_RGBM_0_1" geometry={nodes.pCube967_RGBM_0_1.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube966_1" position={[0.161, -0.055, 1.344]} rotation={[1.885, 0.648, -1.746]} scale={[1, 1, 0.267]}>
              <mesh name="pCube966_RGBM_0_1" geometry={nodes.pCube966_RGBM_0_1.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube965_1" position={[1.15, -0.055, 0.67]} rotation={[2.263, 0.175, -2.615]} scale={[1, 1, 0.267]}>
              <mesh name="pCube965_RGBM_0_1" geometry={nodes.pCube965_RGBM_0_1.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube964_1" position={[1.243, -0.055, -0.468]} rotation={[2.189, -0.376, 2.984]} scale={[1, 1, 0.267]}>
              <mesh name="pCube964_RGBM_0_1" geometry={nodes.pCube964_RGBM_0_1.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube963_1" position={[0.291, -0.055, -1.319]} rotation={[1.566, -0.71, 1.883]} scale={[1, 1, 0.267]}>
              <mesh name="pCube963_RGBM_0_1" geometry={nodes.pCube963_RGBM_0_1.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube962_1" position={[-0.936, -0.055, -1.014]} rotation={[0.953, -0.376, 0.795]} scale={[1, 1, 0.267]}>
              <mesh name="pCube962_RGBM_0_1" geometry={nodes.pCube962_RGBM_0_1.geometry} material={materials.RGBM} />
            </group>
            <group name="pCylinder145_1">
              <mesh name="pCylinder145_Fan2M_0_1" geometry={nodes.pCylinder145_Fan2M_0_1.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube961_1" position={[-1.39, -0.055, 0]} rotation={[0.875, 0.159, 0.131]} scale={[1, 1, 0.267]}>
              <mesh name="pCube961_RGBM_0_1" geometry={nodes.pCube961_RGBM_0_1.geometry} material={materials.RGBM} />
            </group>
            <group name="pCylinder164_1" scale={[1.189, 0.94, 1.189]}>
              <mesh name="pCylinder164_RGBM_0_1" geometry={nodes.pCylinder164_RGBM_0_1.geometry} material={materials.RGBM} />
            </group>
          </group>
        </group>
        <group name="Corsair_Fan2" position={[9.983, -7.293, -7.023]} rotation={[Math.PI / 2, 0, 0]} scale={[0.576, 0.704, 0.576]}>
          <group name="Fan2_2" position={[0.033, -0.014, 0]} scale={[0.772, 0.762, 0.772]}>
            <group name="pCube967_2" position={[-0.895, -0.055, 1.049]} rotation={[1.217, 0.63, -0.692]} scale={[1, 1, 0.267]}>
              <mesh name="pCube967_RGBM_0_2" geometry={nodes.pCube967_RGBM_0_2.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube966_2" position={[0.161, -0.055, 1.344]} rotation={[1.885, 0.648, -1.746]} scale={[1, 1, 0.267]}>
              <mesh name="pCube966_RGBM_0_2" geometry={nodes.pCube966_RGBM_0_2.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube965_2" position={[1.15, -0.055, 0.67]} rotation={[2.263, 0.175, -2.615]} scale={[1, 1, 0.267]}>
              <mesh name="pCube965_RGBM_0_2" geometry={nodes.pCube965_RGBM_0_2.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube964_2" position={[1.243, -0.055, -0.468]} rotation={[2.189, -0.376, 2.984]} scale={[1, 1, 0.267]}>
              <mesh name="pCube964_RGBM_0_2" geometry={nodes.pCube964_RGBM_0_2.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube963_2" position={[0.291, -0.055, -1.319]} rotation={[1.566, -0.71, 1.883]} scale={[1, 1, 0.267]}>
              <mesh name="pCube963_RGBM_0_2" geometry={nodes.pCube963_RGBM_0_2.geometry} material={materials.RGBM} />
            </group>
            <group name="pCube962_2" position={[-0.936, -0.055, -1.014]} rotation={[0.953, -0.376, 0.795]} scale={[1, 1, 0.267]}>
              <mesh name="pCube962_RGBM_0_2" geometry={nodes.pCube962_RGBM_0_2.geometry} material={materials.RGBM} />
            </group>
            <group name="pCylinder145_2">
              <mesh name="pCylinder145_Fan2M_0_2" geometry={nodes.pCylinder145_Fan2M_0_2.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube961_2" position={[-1.39, -0.055, 0]} rotation={[0.875, 0.159, 0.131]} scale={[1, 1, 0.267]}>
              <mesh name="pCube961_RGBM_0_2" geometry={nodes.pCube961_RGBM_0_2.geometry} material={materials.RGBM} />
            </group>
            <group name="pCylinder164_2" scale={[1.189, 0.94, 1.189]}>
              <mesh name="pCylinder164_RGBM_0_2" geometry={nodes.pCylinder164_RGBM_0_2.geometry} material={materials.RGBM} />
            </group>
          </group>
        </group>
        <group name="PSU" position={[4.778, -13.312, 2.6]} rotation={[Math.PI / 2, 0, 0]} scale={1.225}>
          <group name="Fan1" position={[-4.145, -7.282, -3.77]} scale={0.816}>
            <group name="pCube967_3" position={[-0.895, -0.055, 1.049]} rotation={[1.217, 0.63, -0.692]} scale={[1, 1, 0.267]}>
              <mesh name="pCube967_PSUFanM_0" geometry={nodes.pCube967_PSUFanM_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube966_3" position={[0.161, -0.055, 1.344]} rotation={[1.885, 0.648, -1.746]} scale={[1, 1, 0.267]}>
              <mesh name="pCube966_PSUFanM_0" geometry={nodes.pCube966_PSUFanM_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube965_3" position={[1.15, -0.055, 0.67]} rotation={[2.263, 0.175, -2.615]} scale={[1, 1, 0.267]}>
              <mesh name="pCube965_PSUFanM_0" geometry={nodes.pCube965_PSUFanM_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube964_3" position={[1.243, -0.055, -0.468]} rotation={[2.189, -0.376, 2.984]} scale={[1, 1, 0.267]}>
              <mesh name="pCube964_PSUFanM_0" geometry={nodes.pCube964_PSUFanM_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube963_3" position={[0.291, -0.055, -1.319]} rotation={[1.566, -0.71, 1.883]} scale={[1, 1, 0.267]}>
              <mesh name="pCube963_PSUFanM_0" geometry={nodes.pCube963_PSUFanM_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube962_3" position={[-0.936, -0.055, -1.014]} rotation={[0.953, -0.376, 0.795]} scale={[1, 1, 0.267]}>
              <mesh name="pCube962_PSUFanM_0" geometry={nodes.pCube962_PSUFanM_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCylinder145_3">
              <mesh name="pCylinder145_PSUFanM_0" geometry={nodes.pCylinder145_PSUFanM_0.geometry} material={materials.PaletteMaterial001} />
            </group>
            <group name="pCube961_3" position={[-1.39, -0.055, 0]} rotation={[0.875, 0.159, 0.131]} scale={[1, 1, 0.267]}>
              <mesh name="pCube961_PSUFanM_0" geometry={nodes.pCube961_PSUFanM_0.geometry} material={materials.PaletteMaterial001} />
            </group>
          </group>
        </group>
        <mesh name="pCube480_lambert1_0" geometry={nodes.pCube480_lambert1_0.geometry} material={materials.PaletteMaterial001} position={[0.083, 1.964, -7.941]} scale={[0.042, 0.096, 0.011]} />
        <mesh name="pCylinder10_CapacitorsM_0" geometry={nodes.pCylinder10_CapacitorsM_0.geometry} material={materials.CapacitorsM} position={[-3.089, -2.94, -7.857]} rotation={[Math.PI / 2, 0, 0]} scale={[0.062, 0.071, 0.062]} />
        <mesh name="pCube328_BoardPlate2m_0" geometry={nodes.pCube328_BoardPlate2m_0.geometry} material={materials.BoardPlate2m} />
        <mesh name="pCube315_BoardChipsetM_0" geometry={nodes.pCube315_BoardChipsetM_0.geometry} material={materials.BoardChipsetM} position={[0, 0, 0.017]} />
        <mesh name="pCube305_BoardM2CoverM_0" geometry={nodes.pCube305_BoardM2CoverM_0.geometry} material={materials.BoardM2CoverM} position={[0.526, -3.519, -7.607]} scale={[1, 0.69, 0.097]} />
        <mesh name="pCube304_BoardM2Cover1M_0" geometry={nodes.pCube304_BoardM2Cover1M_0.geometry} material={materials.BoardM2Cover1M} position={[0, 0, 0.319]} />
        <mesh name="pCube340_BoardPlate1m_0" geometry={nodes.pCube340_BoardPlate1m_0.geometry} material={materials.BoardPlate1m} position={[0, 0, 0.587]} scale={[1, 1, 1.276]} />
        <mesh name="pCube444_RGBM_0" geometry={nodes.pCube444_RGBM_0.geometry} material={materials.RGBM} position={[-1.948, 2.071, -6.847]} scale={0.137} />
        <mesh name="pCube511_BaseBoardM_0" geometry={nodes.pCube511_BaseBoardM_0.geometry} material={materials.BaseBoardM} />
        <mesh name="pCube851_M2_StickerM_0" geometry={nodes.pCube851_M2_StickerM_0.geometry} material={materials.M2_StickerM} position={[-0.633, -0.393, -7.707]} scale={[0.378, 0.31, 0.009]} />
        <mesh name="pCube842_M2_BaseM_0" geometry={nodes.pCube842_M2_BaseM_0.geometry} material={materials.M2_BaseM} />
        <mesh name="pCube1238_RTXPinsM_0" geometry={nodes.pCube1238_RTXPinsM_0.geometry} material={materials.RTXPinsM} position={[-0.973, -3.845, -6.926]} rotation={[Math.PI / 2, 0, 0]} scale={[4.06, 1, 0.569]} />
        <mesh name="pCylinder156_RTXM2_0" geometry={nodes.pCylinder156_RTXM2_0.geometry} material={materials.RTXM2} position={[-1.69, -2.819, -2.294]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="pCube1000_RTXM3_0" geometry={nodes.pCube1000_RTXM3_0.geometry} material={materials.RTXM3} position={[0.022, -0.595, -8.096]} />
        <mesh name="pCube1169_RTXM1_0" geometry={nodes.pCube1169_RTXM1_0.geometry} material={materials.RTXM1} position={[0.022, -0.595, -8.096]} />
        <mesh name="pCube902_Ram3M_0" geometry={nodes.pCube902_Ram3M_0.geometry} material={materials.Ram3M} position={[-0.062, -0.007, -1.022]} />
        <mesh name="pCube910_Ram4M_0" geometry={nodes.pCube910_Ram4M_0.geometry} material={materials.Ram4M} position={[4.508, 3.768, -1.066]} rotation={[0, 0, Math.PI]} scale={[0.58, 1, 1]} />
        <mesh name="pCube920_Ram2M_0" geometry={nodes.pCube920_Ram2M_0.geometry} material={materials.Ram2M} position={[0.634, -0.007, -1.022]} />
        <mesh name="SSD_SSDM_0" geometry={nodes.SSD_SSDM_0.geometry} material={materials.SSDM} position={[9.516, -4.372, -16.75]} rotation={[Math.PI, 0, -Math.PI / 2]} scale={1.146} />
        <mesh name="pCylinder188_TubingM_0" geometry={nodes.pCylinder188_TubingM_0.geometry} material={materials.PaletteMaterial002} position={[5.956, 1.27, -6.945]} />
        <mesh name="GlassFront_GlassM_0" geometry={nodes.GlassFront_GlassM_0.geometry} material={materials.PaletteMaterial003} position={[0, 0, 0.702]} />
      </group>
    </group>
  )
}

useGLTF.preload('/comp-transformed.glb')
